### ISSUE TITLE
Setting status  frame reporting time

### ISSUE THREAD

**Issue by Crossle86** [CrossTheRoadElec/Phoenix-Releases#17]
I am using both TalonSRX and TalonFX and want to etStatusFramePeriod() for each type of controller. I am interested in reducing the reporting time for the SRX magnetic encoder plugged into the talon, so would that be frame type 2 or 3? And when selecting feedback device, is the device in this case "integrated" or "quadrature"?

On the FX, I am interested in reducing the integrated encoder reporting time. Your doc indicates frame type 21, but that type is not in the frame enum and I can't find a constant value to use.

**Comment by JCaporuscio** [comment]
Which frame you speed up depends on which API you're using.
If you're doing closed-looping and have the mag encoder (or FX's integrated sensor) as your selected sensor and you're using getSelectedSensorPosition()/Velocity(), then you only need to speed up Status 2.

Status 3 (for SRX quad) and Status 21 (for FX integrated) contain the data that's used when you call SensorCollection methods to directly access quad or integrated data.  If you're not using the SensorCollection functions on a periodic basis (which most of the time isn't necessary) then you don't need to speed them up.

You're correct that it looks like Status 21 is missing from the enum.  We can get that fixed in an upcoming release and we can provide the enum value if you need it sooner for your application.

**Comment by Crossle86** [comment]
I'm confused. I have been using the sensor collection for srx magnetic by calling getSensorCollection().getQuadraturePosition. This seems to work but now I am wondering. I see now you can select with an enum specific to srx mag. Some years ago when I  coded my wrapper for srx mag I don't think that was available so I went with sensorcollection. Maybe I have been doing this wrong all along. But it does count and we have used the code successfully. But I am calling getQuadrature...

I want to read the srx mag and fx integrated and set the correct frame time to control the response for these two sensors. Seems like I can select srx mag or fx integrated then call getSelectedSensorPosition and adjust frame 2 for both.

**Comment by JCaporuscio** [comment]
> Seems like I can select srx mag or fx integrated then call getSelectedSensorPosition and adjust frame 2 for both.
That's correct

**Comment by Crossle86** [comment]
Ok, so using sensorcollection may have been based on a misunderstanding of the doc some 8 years ago when the code was first written. Using getSelectedSensorPosition() is definately faster as documented.

One new question, we were using the sensorcollection.getintegratedSensorPosition and counts were returned and had a sign, negative in this case. So we inverted the encoder in calling code since we wanted positive counts. When I switched to getSelectedSensorPosition() the sign of the counts returned changed and I had to remove the call to invert the encoder. Is that expected? I would have though both calls would return the same sign.

**Comment by JCaporuscio** [comment]
You're correct that the signage of sensorcollection.getIntegratedSensorPosition() and getSelectedSensorPosition() may be different.

This is because sensor collection methods do not modify signage in any way - it's always the raw sensor value.

getSelectedSensorPosition(), however, takes into account any motor inverting (ie when you invert the motor direction the sensor direction is automatically inverted to keep the sensor in phase with the motor).  It also takes into account the manually set sensor phase in the case of the SRX.  This is the other primary reason besides update speed that you should use the Selected Sensor calls - they give you the same sensor value that will be used by your closed-looping.

**Comment by Crossle86** [comment]
Makes sense. Thanks for the help.
